<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('FEATURED PRODUCTS');
    $items = $block->getProductCollection()->addFieldToFilter('is_featured', 1)->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
}
?>

<?php if ($exist):?>
    <section class="section section-products clearfix">
        <div class="section-title">
            <h2 class="title"><?php /* @escapeNotVerified */ echo $title; ?></h2>
        </div>
        <div class="section-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div id="owl-products" class="owl-carousel owl-theme">
                <div class="item">
                    <div class="list-products">
                        <ul class="row">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-xs-12 col-sm-6 col-md-3">' : '</li><li class="col-xs-12 col-sm-6 col-md-3">' ?>
                                <div class="products">
                                    <div class="product-transition">
                                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                            <?php
                                            $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                                            $images = $product->getMediaGalleryImages();
                                            $count  = 1;
                                            ?>
                                            <?php if($count <=2 ):?>
                                                <?php  foreach ($images as $img):?>
                                                    <img class="img-<?php echo $count ?>" src="<?php echo $img->getUrl() ?>" alt="">
                                                <?php $count++; endforeach ?>
                                            <?php endif?>
                                        </a>
                                        <div class="product-action">
                                            <a class="view-product" data-toggle="modal" data-target="#myModal">
                                                <span class="mdi mdi-eye"></span>
                                            </a>
                                            <?php if ($showCart): ?>
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <a href="#"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span class="mdi mdi-wallet-travel"></span>
                                                        </a>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                            <a href="#"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                <span class="mdi mdi-wallet-travel"></span>
                                                            </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php endif ?>
                                            <?php if($showCompare): ?>
                                                <a href="#">
                                                    <span class="mdi mdi-swap-horizontal"></span>
                                                </a>
                                            <?php endif ?>
                                        </div>
                                        <div class="entry heart">
                                            <a href="#">
                                                <i class="fa fa-heart-o" aria-hidden="true"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="product-entry">
                                        <h3 class="product-title">
                                            <a  title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                        </h3>
                                            <span class="price">
                                                <span class="price-amount amount">
                                                   <?php
                                                        echo $block->getProductPriceHtml($_item, $type);
                                                   ?>
                                                </span>
                                            </span>
                                    </div>
                                </div>
                                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ul>
                    </div>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </section>
<?php endif;?>
