<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('FEATURED PRODUCTS');
    $items = $block->getProductCollection()->addFieldToFilter('is_featured', 1)->setOrder('sort_order', 'ASC')->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $countList = 0;
}
?>

<?php if ($exist):?>
    <section class="section section-products clearfix">
        <div class="container">
            <div class="section-title">
                <h2 class="title"><?php /* @escapeNotVerified */ echo $title; ?></h2>
            </div>
            <div class="section-content">
                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                <div id="owl-products" class="owl-carousel owl-theme">
                    <div class="item">
                        <div class="list-products">
                            <ul class="row">
                                <?php $iterator = 1; ?>
                                <?php foreach ($items as $_item): ?>
                                    <?php $countList++; ?>
                                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-xs-12 col-sm-6 col-md-3">' : '</li><li class="col-xs-12 col-sm-6 col-md-3">' ?>
                                    <div class="products">
                                        <div class="product-transition">
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                                <?php
                                                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                                                $images = $product->getMediaGalleryImages();
                                                $count  = 1;
                                                ?>
                                                <?php if($count <=2 ):?>
                                                    <?php  foreach ($images as $img):?>
                                                        <img class="img-<?php echo $count ?>" src="<?php echo $img->getUrl() ?>" alt="">
                                                    <?php $count++; endforeach ?>
                                                <?php endif?>
                                            </a>
                                            <div class="product-action">
                                                <a class="view-product" href="#" data-toggle="modal" data-target="#view-<?php echo $_item->getId();?>">
                                                    <span class="mdi mdi-eye"></span>
                                                </a>
                                                <?php if ($showCart): ?>
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <a href="#"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                <span class="mdi mdi-wallet-travel"></span>
                                                            </a>
                                                        <?php else: ?>
                                                            <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                                <a href="#"
                                                                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span class="mdi mdi-wallet-travel"></span>
                                                                </a>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endif ?>
                                                <?php if($showCompare): ?>
                                                    <a href="#">
                                                        <span class="mdi mdi-swap-horizontal"></span>
                                                    </a>
                                                <?php endif ?>
                                            </div>
                                            <div class="entry heart">
                                                <a href="#">
                                                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="product-entry">
                                            <h3 class="product-title">
                                                <a  title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                    href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                    <?php echo $block->escapeHtml($_item->getName()) ?></a>
                                            </h3>
                                                <span class="price">
                                                    <span class="price-amount amount">
                                                       <?php
                                                            echo $block->getProductPriceHtml($_item, $type);
                                                       ?>
                                                    </span>
                                                </span>
                                        </div>
                                    </div>
                                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                                    <?php echo($countList%8 == 0) ? '</ul></div></div><div class="item"><div class="list-products"><ul class="row">' : '' ?>
                                <?php endforeach ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </div>
    </section>
    <?php foreach ($items as $_item): ?>
        <!--    quick view -->
        <div class="content-product modal fade" id="view-<?php echo $_item->getId();?>" tabindex="-1" role="dialog" aria-labelledby="<?php echo $_item->getId();?>">
            <div class="modal-dialog single-content" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="single-product-content">
                            <div class="row">
                                <div class="col-xs-12 col-sm-6 col-md-5 product-gallery">
                                    <ul>
                                        <li>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                <img alt="#" src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_item->getImage();?>">
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-xs-12 col-sm-6 col-md-7 entry-summary">
                                    <div class="product-entry">
                                        <h2>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </h2>
											<span class="price">
												<span class="price-amount amount">
													<?php echo $block->getProductPriceHtml($_item, $type); ?>
												</span>
											</span>
                                        <p class="stars">
                                            <?php if ($templateType): ?>
                                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>
                                        </p>
                                        <div class="description">
                                            <?php echo $_item->getShortDescription(); ?>
                                        </div>
                                        <div class="variations clearfix">
                                            <div class="size">
                                                <p>SIZE</p>
													<span>
														<a href="#">S</a>
													</span>
													<span>
														<a href="#">M</a>
													</span>
													<span>
														<a href="#">L</a>
													</span>
													<span>
														<a href="#">XL</a>
													</span>
                                            </div>
                                            <div class="color">
                                                <p>COLOR </p>
													<span class="cl-10">
														<a href="#"></a>
													</span>
													<span class="cl-7">
														<a href="#"></a>
													</span>
													<span>
														<a href="#"></a>
													</span>
                                            </div>
                                        </div>
                                        <div class="product-meta clearfix">
												<span>Availability :
													<a href="#">In stock</a>
												</span>
												<span class="category">Category :
													<a href="#">Woman</a>
												</span>
												<span>Tag :
													<a href="#">Coat</a>
												</span>
                                        </div>
                                        <div class="quantity">
                                            <input type="number" min="1" max="999" step="1" value="1">
                                            <div class="quantity-nav">
                                                <div class="quantity-button quantity-up">
                                                    <i class="mdi mdi-chevron-up"></i>
                                                </div>
                                                <div class="quantity-button quantity-down">
                                                    <i class="mdi mdi-chevron-down"></i>
                                                </div>
                                            </div>
                                            <p class="btn-bottom">
                                                <a class="au-btn au-btn-primary m-r-5" href="#">Add to cart</a>
                                            </p>
                                        </div>
                                        <div class="product-button clearfix">
                                            <a class="width" href="#">
                                                <span class="mdi mdi-heart-outline"></span>Add to wishlist</a>
                                            <a class="width" href="#">
                                                <span class="mdi mdi-swap-horizontal"></span>Compare</a>
												<span class="width share">Share :
													<a href="#">
														<span class="mdi mdi-facebook"></span>
													</a>
													<a href="#">
														<span class="mdi mdi-dribbble"></span>
													</a>
													<a href="#">
														<span class="mdi mdi-google"></span>
													</a>
													<a href="#">
														<span class="mdi mdi-twitter"></span>
													</a>
												</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--    end quick view -->
    <?php endforeach ?>
<?php endif;?>
