<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('FEATURED PRODUCTS');
    $items = $block->getProductCollection()->addFieldToFilter('is_featured', 1)->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
}
?>

<?php if ($exist):?>
    <section class="section section-products clearfix">
        <div class="section-title">
            <h2 class="title"><?php /* @escapeNotVerified */ echo $title; ?></h2>
        </div>
        <div class="section-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div id="owl-products" class="owl-carousel owl-theme">
                <div class="item">
                    <div class="list-products">
                        <ul class="row">
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item): ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="col-xs-12 col-sm-6 col-md-3">' : '</li><li class="col-xs-12 col-sm-6 col-md-3">' ?>
                                <div class="products">
                                    <div class="product-transition">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php
                                        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                                        $images = $product->getMediaGalleryImages();
                                        $count  = 1;
                                        //$images = array_slice($images, 0, 2);
                                        ?>

                                        <?php  foreach ($images as $img):?>
                                            <img class="img-<?php echo $count ?>" src="<?php echo $img->getUrl() ?>" alt="">
                                        <?php $count++; endforeach ?>
                                    </a>
                                    </div>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                               class="product-item-link">
                                                <?php echo $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php
                                        echo $block->getProductPriceHtml($_item, $type);
                                        ?>

                                        <?php if ($templateType): ?>
                                            <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                        <?php endif; ?>

                                        <?php if ($showWishlist || $showCompare || $showCart): ?>
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="action tocart primary"
                                                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary"
                                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <div class="actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                               class="action towishlist" data-action="add-to-wishlist"
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                            <a href="#" class="action tocompare"
                                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ul>
                    </div>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </section>
<?php endif;?>
