<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form subscribe"
      novalidate
      action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="newsletter-validate-detail">

      <input name="email" type="text" id="newsletter" class="text-mail"
           placeholder="<?php /* @escapeNotVerified */ echo __('Your Email....') ?>"
           data-validate="{required:true, 'validate-email':true}"/>

      <button class="footer-btn" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
          <span class="mdi mdi-send"></span>
      </button>
    </div>
</form>
